function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "mpcprueba2"};
	this.sidHashMap["mpcprueba2"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "mpcprueba2:378"};
	this.sidHashMap["mpcprueba2:378"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "mpcprueba2:379"};
	this.sidHashMap["mpcprueba2:379"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Constant2"] = {sid: "mpcprueba2:408"};
	this.sidHashMap["mpcprueba2:408"] = {rtwname: "<Root>/Constant2"};
	this.rtwnameHashMap["<Root>/Constant4"] = {sid: "mpcprueba2:409"};
	this.sidHashMap["mpcprueba2:409"] = {rtwname: "<Root>/Constant4"};
	this.rtwnameHashMap["<Root>/Constant5"] = {sid: "mpcprueba2:410"};
	this.sidHashMap["mpcprueba2:410"] = {rtwname: "<Root>/Constant5"};
	this.rtwnameHashMap["<Root>/Demux"] = {sid: "mpcprueba2:373"};
	this.sidHashMap["mpcprueba2:373"] = {rtwname: "<Root>/Demux"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "mpcprueba2:414"};
	this.sidHashMap["mpcprueba2:414"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/Display1"] = {sid: "mpcprueba2:416"};
	this.sidHashMap["mpcprueba2:416"] = {rtwname: "<Root>/Display1"};
	this.rtwnameHashMap["<Root>/Display2"] = {sid: "mpcprueba2:417"};
	this.sidHashMap["mpcprueba2:417"] = {rtwname: "<Root>/Display2"};
	this.rtwnameHashMap["<Root>/Display3"] = {sid: "mpcprueba2:418"};
	this.sidHashMap["mpcprueba2:418"] = {rtwname: "<Root>/Display3"};
	this.rtwnameHashMap["<Root>/MATLAB Function"] = {sid: "mpcprueba2:378"};
	this.sidHashMap["mpcprueba2:378"] = {rtwname: "<Root>/MATLAB Function"};
	this.rtwnameHashMap["<Root>/MATLAB Function5"] = {sid: "mpcprueba2:379"};
	this.sidHashMap["mpcprueba2:379"] = {rtwname: "<Root>/MATLAB Function5"};
	this.rtwnameHashMap["<Root>/Mux"] = {sid: "mpcprueba2:380"};
	this.sidHashMap["mpcprueba2:380"] = {rtwname: "<Root>/Mux"};
	this.rtwnameHashMap["<Root>/Saturation"] = {sid: "mpcprueba2:381"};
	this.sidHashMap["mpcprueba2:381"] = {rtwname: "<Root>/Saturation"};
	this.rtwnameHashMap["<Root>/Saturation1"] = {sid: "mpcprueba2:382"};
	this.sidHashMap["mpcprueba2:382"] = {rtwname: "<Root>/Saturation1"};
	this.rtwnameHashMap["<Root>/Saturation2"] = {sid: "mpcprueba2:383"};
	this.sidHashMap["mpcprueba2:383"] = {rtwname: "<Root>/Saturation2"};
	this.rtwnameHashMap["<Root>/Saturation3"] = {sid: "mpcprueba2:384"};
	this.sidHashMap["mpcprueba2:384"] = {rtwname: "<Root>/Saturation3"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "mpcprueba2:385"};
	this.sidHashMap["mpcprueba2:385"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "mpcprueba2:378:1"};
	this.sidHashMap["mpcprueba2:378:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "mpcprueba2:379:1"};
	this.sidHashMap["mpcprueba2:379:1"] = {rtwname: "<S2>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
